### ISSUE TITLE
ocrd resmgr download broken

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#1076]
```
[tmp.21473]mike@b-pc30533 ~ % ocrd resmgr download ocrd-eynollah-segment default
19:13:20.736 INFO ocrd.cli.resmgr - Downloading resource {'url': 'https://qurator-data.de/eynollah/models_eynollah.tar.gz', 'name': 'default', 'description': 'models for eynollah', 'size': 3241866640, 'type': 'tarball', 'path_in_archive': 'models_eynollah', 'parameter_usage': 'as-is', 'version_range': '>= 0.0.1'}
  [------------------------------------]    0%19:13:20.737 INFO ocrd.resource_manager._download_impl - Downloading https://qurator-data.de/eynollah/models_eynollah.tar.gz to download.tar.xx
19:13:20.850 INFO ocrd.resource_manager.download - Extracting tarball

Traceback (most recent call last):
  File "/home/mike/.local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/.local/lib/python3.9/site-packages/ocrd/cli/resmgr.py", line 134, in download
    fpath = resmgr.download(
  File "/home/mike/.local/lib/python3.9/site-packages/ocrd/resource_manager.py", line 222, in download
    with open_tarfile('../download.tar.xx', 'r:*') as tar:
  File "/usr/lib64/python3.9/tarfile.py", line 1625, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

It does not seem to downloading anything and then failing to read the non-existing tarball. eynollah main branch + ocrd 2.52.0

**Comment by mikegerber** [comment]
This seems to have been a missing `rehash` here and thus working with a different `ocrd` ... One day I will learn, sorry for the noise.
