### ISSUE TITLE
workspace validator: non-URI path

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#1179]
From a `workspace validate` I got:
```XML
<report valid="false">
  <error>METS has no unique identifier</error>
  <error>Validation aborted with exception: Traceback (most recent call last):
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/ocrd_validators/workspace_validator.py", line 149, in _validate
    self._validate_mets_files()
  File "/data/ocr-d/ocrd_all/venv38/lib/python3.8/site-packages/ocrd_validators/workspace_validator.py", line 302, in _validate_mets_files
    scheme = f.url[0:f.url.index(':')]
ValueError: substring not found
</error>
</report>
```

The `url` in question simply was a relative file name, which obviously makes the [URI validator](https://github.com/OCR-D/core/blob/e9c20e092aa01351ddb67f0f6bb7eb8e6f439cfb/src/ocrd_validators/workspace_validator.py#L302) crash.

This is very problematic for two reasons:
1. before ocrd differentiated between LOCTYPE=URL and OTHER, we created lots of data (including GT) with URL, despite being local paths – this now broke
2. in this case, the data was just **created by current ocrd** itself – via `ocrd workspace add`, because that implementation [sets both `local_filename` and `url` to the local path](https://github.com/OCR-D/core/blob/ae6efca76b62b8375347028fd8145b241b6fb85b/src/ocrd/cli/workspace.py#L217-L246)

**Comment by mikegerber** [comment]
Yeah, this happens with a workspace built with `ocrd workspace` itself...

add seems to make for example this:

```
      <mets:file ID="XXX" MIMETYPE="image/jpeg">
        <mets:FLocat xlink:href="OCR-D-IMG/2812988X_1862-09-02_001.jpg" LOCTYPE="OTHER" OTHERLOCTYPE="FILE"/>
        <mets:FLocat xlink:href="OCR-D-IMG/2812988X_1862-09-02_001.jpg" LOCTYPE="URL"/>
      </mets:file>
```

**Comment by mikegerber** [comment]
Removing the FLocats with `LOCTYPE="URL"` and making the image filename referenced in the PAGE XML (I imported) consistent fixes the validation at least (in the sense that it doesn't choke on exceptions itself).

**Comment by mikegerber** [comment]
`add` also created this structMap:

```xml
  <mets:structMap TYPE="PHYSICAL">
    <mets:div TYPE="physSequence">
      <mets:div TYPE="page" ID="PAGE_1">
        <mets:fptr FILEID="XXX"/>
      </mets:div>
      <mets:div TYPE="page" ID="PAGE_1">
        <mets:fptr FILEID="XXX2"/>
      </mets:div>
      <mets:div TYPE="page" ID="PAGE_1">
        <mets:fptr FILEID="XXX3"/>
      </mets:div>
    </mets:div>
  </mets:structMap>
```

which seemed to have broken iterating over the pages in `ocrd-sbb-binarize`. This should be - unless this is valid contrary to my belief - exactly one `div` with ID `PAGE_1`. (File `XXX2` also should even be in there anymore as I `remove-group`ed the fileGrp.)

(All latest ocrd/all:maximum)

**Comment by mikegerber** [comment]
> But this is a **separate issue** (has nothing to do with the validator).

True, I'll open another GitHub issue for that, if you didn't already.

**Comment by bertsky** [comment]
> I'll open another GitHub issue for that, if you didn't already.

No, please do!

**Comment by bertsky** [comment]
With 2. solved in #1199, only 1. is left.

The URI validator should not crash – it should first check if the href is in fact a URI and then simply add a specific `error` to the report.
