### ISSUE TITLE
Error in `to_xml`

### ISSUE THREAD

**Issue by finkf** [OCR-D/core#148]
I use `to_xml` to write a new page-xml file:
```python
    def write_alignment_to_xml(self, ogroup):
        master = self.ifs[0]
        pcgts = from_file(self.process.workspace.download_file(master)
        self.process.add_output_file(
            ID= "{}-{}".format(ogroup, master.ID),
            mimetype=MIMETYPE_PAGE,
            content=to_xml(pcgts),
            file_grp=ogroup,
            basename=master.basename,
        )
```
Produces the following error:
```bash
Traceback (most recent call last):
  File "/tmp/cis-ocrd-py-cache/env/bin/cis-ocrd-align", line 11, in <module>
    sys.exit(cis_ocrd_align())
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/align/cli.py", line 10, in cis_ocrd_align
    return ocrd_cli_wrap_processor(Aligner, *args, **kwargs)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/decorators.py", line 24, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/processor/base.py", line 62, in run_processor
    processor.process()
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/align/aligner.py", line 30, in process
    pa.write_alignment_to_xml(self.output_file_grp)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/align/aligner.py", line 115, in write_alignment_to_xml
    content=to_xml(pcgts),
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page.py", line 32, in to_xml
    el.export(sio, 0, name_='PcGts', namespacedef_='xmlns:pc="%s"' % NAMESPACES['page'])
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 770, in export
    self.exportChildren(outfile, level + 1, namespace_='pc:', name_='PcGtsType', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 787, in exportChildren
    self.Page.export(outfile, level, namespace_, name_='Page', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 1580, in export
    self.exportChildren(outfile, level + 1, namespace_='pc:', name_='PageType', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 1653, in exportChildren
    TextRegion_.export(outfile, level, namespace_, name_='TextRegion', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 8051, in export
    self.exportChildren(outfile, level + 1, namespace_='pc:', name_='TextRegionType', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 8104, in exportChildren
    TextLine_.export(outfile, level, namespace_, name_='TextLine', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 2088, in export
    self.exportChildren(outfile, level + 1, namespace_='pc:', name_='TextLineType', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 2135, in exportChildren
    TextEquiv_.export(outfile, level, namespace_, name_='TextEquiv', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 2786, in export
    self.exportChildren(outfile, level + 1, namespace_='pc:', name_='TextEquivType', pretty_print=pretty_print)
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 2817, in exportChildren
    outfile.write('<pc:Unicode>%s</pc:Unicode>%s' % (self.gds_encode(self.gds_format_string(quote_xml(self.Unicode), input_name='Unicode')), eol_))
  File "/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 476, in quote_xml
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
TypeError: not all arguments converted during string formatting
```

**Comment by kba** [comment]
That's an issue in the XSD-generated code for accessing Page XML. Can you step through / add print statements to the code to see what `inStr` actually is at `"/tmp/cis-ocrd-py-cache/env/lib/python3.6/site-packages/ocrd/model/ocrd_page_generateds.py", line 476, in quote_xml`? Could be a bug in generateDS when the string is somehting like `%s` itself.

Feel free to join the chat at https://gitter.im/OCR-D/Lobby, might be quicker for debugging.

**Comment by finkf** [comment]
Thanks. I found the error. I set Unicode to be a tuple not a string. Closing
