### ISSUE TITLE
Using a non-existent file group as input should give an error message

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#251]
Using a non-existent file group as input should give an error message:

~~~
cd `mktemp -d`
wget https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/61aeac32-ef0a-443d-820b-5db7bf8fc8a3/data/lohenstein_agrippina_1665.ocrd.zip
unzip lohenstein_agrippina_1665.ocrd.zip
cd lohenstein_agrippina_1665.ocrd/data
ocrd-tesserocr-segment-line   -l DEBUG -m mets.xml -I DOES-NOT-EXIST -O OCR-D-SEG-LINE
~~~

This is a NOP, but should give an error because DOES-NOT-EXIST does not exist!

See also https://github.com/OCR-D/ocrd_tesserocr/issues/47.

**Comment by bertsky** [comment]
So how about it? Should be easy to fix, right?

**Comment by bertsky** [comment]
In addition, already existing file groups as __output__ should be fatal. 

Both, input and output checks should happen **before** running the processor (taking up space and time, overwriting files).

I believe all this is already implemented in `ocrd process` via `task_sequence.run_tasks`, which raises exceptions in both cases. But we need this for the independent CLIs (`decorators.ocrd_cli_wrap_processor` which calls `processor.base.run_processor`) as well!

**Comment by EEngl52** [comment]
@kba can this be closed?

**Comment by kba** [comment]
```
2020-04-23 20:15:29.157 INFO ocrd.workspace_validator - input_file_grp=['DOES-NOT-EXIST'] output_file_grp=['OCR-D-SEG-LINE']                                                
Traceback (most recent call last):
  File "/home/kba/env/py3/bin/ocrd-tesserocr-segment-line", line 11, in <module>
    load_entry_point('ocrd-tesserocr', 'console_scripts', 'ocrd-tesserocr-segment-line')()                                                                                  
  File "/home/kba/env/py3/lib/python3.6/site-packages/click/core.py", line 829, in __call__                                                                                 
    return self.main(*args, **kwargs)
  File "/home/kba/env/py3/lib/python3.6/site-packages/click/core.py", line 782, in main                                                                                     
    rv = self.invoke(ctx)
  File "/home/kba/env/py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke                                                                                  
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kba/env/py3/lib/python3.6/site-packages/click/core.py", line 610, in invoke                                                                                   
    return callback(*args, **kwargs)
  File "/home/kba/build/github.com/OCR-D/monorepo/ocrd_tesserocr/ocrd_tesserocr/cli.py", line 26, in ocrd_tesserocr_segment_line                                            
    return ocrd_cli_wrap_processor(TesserocrSegmentLine, *args, **kwargs)
  File "/home/kba/build/github.com/OCR-D/monorepo/core/ocrd/ocrd/decorators.py", line 53, in ocrd_cli_wrap_processor                                                        
    raise Exception("Invalid input/output file grps:\n\t%s" % '\n\t'.join(report.errors))                                                                                   
Exception: Invalid input/output file grps:
        Input fileGrp[@USE='DOES-NOT-EXIST'] not in METS
```

So it now fails as expected. Thanks for raising this.

**Comment by mikegerber** [comment]
Thanks for fixing :+1:
