### ISSUE TITLE
ocrd process does not work with ocropy in docker

### ISSUE THREAD

**Issue by beckstefan** [OCR-D/core#589]
When calling `cis-ocropy-binarize` tool with `ocrd process`

```
docker run --rm -u $(id -u) -v data/:/data -w /data -- ocrd/all:maximum-git ocrd process 'cis-ocropy-binarize -I OCR-D-IMG -O OCR-D-SEG-PAGE'
```

I get following error:

```
Traceback (most recent call last):
  File "/usr/bin/ocrd", line 33, in <module>
    sys.exit(load_entry_point('ocrd', 'console_scripts', 'ocrd')())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/build/core/ocrd/ocrd/cli/process.py", line 27, in process_cli
    run_tasks(mets, log_level, page_id, tasks, overwrite)
  File "/build/core/ocrd/ocrd/task_sequence.py", line 130, in run_tasks
    validate_tasks(tasks, workspace, page_id, overwrite)
  File "/build/core/ocrd/ocrd/task_sequence.py", line 99, in validate_tasks
    first_task.validate()
  File "/build/core/ocrd/ocrd/task_sequence.py", line 73, in validate
    param_validator = ParameterValidator(self.ocrd_tool_json)
  File "/build/core/ocrd/ocrd/task_sequence.py", line 54, in ocrd_tool_json
    self._ocrd_tool_json = json.loads(result.stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```
This was at least true for `cis-ocropy-deskew`. Calling the processes directly within the docker image works fine.

The docker image is up-to-date.

I am not sure if this is related to #540

**Comment by kba** [comment]
What is the output of

```
docker run --rm -u $(id -u) -v data/:/data -w /data -- ocrd/all:maximum-git ocrd-cis-ocropy-binarize --dump-json
```

**Comment by beckstefan** [comment]
```
2020-09-04 09:00:31,823.823 WARNING matplotlib - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-yiekjeyu because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2020-09-04 09:00:31,861.861 INFO matplotlib.font_manager - Generating new fontManager, this may take some time...
{
 "executable": "ocrd-cis-ocropy-binarize",
 "categories": [
  "Image preprocessing"
 ],
 "steps": [
  "preprocessing/optimization/binarization",
  "preprocessing/optimization/grayscale_normalization",
  "preprocessing/optimization/deskewing"
 ],
 "input_file_grp": [
  "OCR-D-IMG",
  "OCR-D-SEG-BLOCK",
  "OCR-D-SEG-LINE"
 ],
 "output_file_grp": [
  "OCR-D-IMG-BIN",
  "OCR-D-SEG-BLOCK",
  "OCR-D-SEG-LINE"
 ],
 "description": "Binarize (and optionally deskew/despeckle) pages / regions / lines with ocropy",
 "parameters": {
  "method": {
   "type": "string",
   "enum": [
    "none",
    "global",
    "otsu",
    "gauss-otsu",
    "ocropy"
   ],
   "description": "binarization method to use (only 'ocropy' will include deskewing and denoising)",
   "default": "ocropy"
  },
  "threshold": {
   "type": "number",
   "format": "float",
   "description": "for the 'ocropy' and ' global' method, black/white threshold to apply on the whitelevel normalized image (the larger the more/heavier foreground)",
   "default": 0.5
  },
  "grayscale": {
   "type": "boolean",
   "description": "for the 'ocropy' method, produce grayscale-normalized instead of thresholded image",
   "default": false
  },
  "maxskew": {
   "type": "number",
   "format": "float",
   "description": "modulus of maximum skewing angle (in degrees) to detect (larger will be slower, 0 will deactivate deskewing)",
   "default": 0.0
  },
  "noise_maxsize": {
   "type": "number",
   "format": "int",
   "description": "maximum pixel number for connected components to regard as noise (0 will deactivate denoising)",
   "default": 0
  },
  "dpi": {
   "type": "number",
   "format": "float",
   "description": "pixel density in dots per inch (overrides any meta-data in the images); disabled when zero or negative",
   "default": 0
  },
  "level-of-operation": {
   "type": "string",
   "enum": [
    "page",
    "region",
    "line"
   ],
   "description": "PAGE XML hierarchy level granularity to annotate images for",
   "default": "page"
  }
 }
}
```

**Comment by kba** [comment]
Thanks, that's indeed a bug, I'll make the json parsing more robust against log messages. Need to investigate why https://github.com/OCR-D/core/pull/548 doesn't fix this.

**Comment by bertsky** [comment]
> Need to investigate why #548 doesn't fix this.

@kba as I said in #540, other loggers from module import time already interfere even before the click command function is entered. This would also affect `-C`, `-L` etc. So the initial logging setup (leading up to `logging.basicConfig`) needs to be targeted. Probably all logging should be `OFF` by default, and enabled only when entering `process()`.

(The same is probably true for some subcommands of `ocrd`...)

**Comment by kba** [comment]
> > Need to investigate why #548 doesn't fix this.
> 
> @kba as I said in #540, other loggers from module import time already interfere even before the click command function is entered. This would also affect `-C`, `-L` etc. So the initial logging setup (leading up to `logging.basicConfig`) needs to be targeted. Probably all logging should be `OFF` by default, and enabled only when entering `process()`.
> 
> (The same is probably true for some subcommands of `ocrd`...)

Yes, I'll try to catch these log messages earlier and/or make the JSON parsing robust to pre/post/interspersed log messages.

I'm wondering why these particular log messages appear in the docker version but not locally.

**Comment by kba** [comment]
Also, why is the log format different in docker?

```
$ docker run -u $(id -u) -v /tmp:/data --rm -it ocrd/all:minimum ocrd log info foo
2020-09-04 11:11:43,513.513 INFO root - foo
$ ocrd log info foo
11:11:51.714 INFO root - foo
```
