### ISSUE TITLE
ocrd process should output STDOUT and STDERR

### ISSUE THREAD

**Issue by stweil** [OCR-D/core#601]
The processor `fileformat-transform` aborts a transformation from PAGE to ALTO when the PAGE input contains negative word coordinates. If it is called directly via `ocrd-fileformat-transform` it stops without any error message. If it is called as part of `ocrd process`, there is at least some (insufficient) information:

    10:36:32.225 INFO ocrd.task_sequence.run_tasks - Start processing task 'fileformat-transform -I OCR-D-OCR-TESS -O OCR-D-OCR-ALTO -p '{"from-to": "page alto", "ext": ".xml", "script-args": ""}''
    Traceback (most recent call last):
      File "/venv-20200912/bin/ocrd", line 8, in <module>
        sys.exit(cli())
      File "/venv-20200912/lib/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/venv-20200912/lib/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/venv-20200912/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/venv-20200912/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/venv-20200912/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/venv-20200912/lib/python3.7/site-packages/ocrd/cli/process.py", line 28, in process_cli
        run_tasks(mets, log_level, page_id, tasks, overwrite)
      File "/venv-20200912/lib/python3.7/site-packages/ocrd/task_sequence.py", line 149, in run_tasks
        raise Exception("%s exited with non-zero return value %s. STDOUT:\n%s\nSTDERR:\n%s" % (task.executable, returncode, out, err))
    Exception: ocrd-fileformat-transform exited with non-zero return value 1. STDOUT:

    STDERR:
    10:36:34.852 INFO ocrd-fileformat-transform - page --> alto: input file FILE_0001_OCR-D-OCR-TESS (PHYS_0001)
    10:36:36.554 INFO ocrd-fileformat-transform - Successfully executed: ocr-transform page alto OCR-D-OCR-TESS/FILE_0001_OCR-D-OCR-TESS.xml OCR-D-OCR-ALTO/FILE_0001_OCR-D-OCR-ALTO.xml -- 
    10:36:36.948 INFO ocrd.workspace - Saving mets '/ocrd_all/pilot/urn:nbn:de:bsz:180-digad-35210/urn:nbn:de:bsz:180-digad-35210/mets.xml'
    10:36:37.394 INFO ocrd-fileformat-transform - page --> alto: input file FILE_0002_OCR-D-OCR-TESS (PHYS_0002)
    10:36:39.072 INFO ocrd-fileformat-transform - Successfully executed: ocr-transform page alto OCR-D-OCR-TESS/FILE_0002_OCR-D-OCR-TESS.xml OCR-D-OCR-ALTO/FILE_0002_OCR-D-OCR-ALTO.xml -- 
    10:36:39.469 INFO ocrd.workspace - Saving mets '/ocrd_all/pilot/urn:nbn:de:bsz:180-digad-35210/urn:nbn:de:bsz:180-digad-35210/mets.xml'
    10:36:39.907 INFO ocrd-fileformat-transform - page --> alto: input file FILE_0003_OCR-D-OCR-TESS (PHYS_0003)

A direct call of `ocr-transform` on the page with the negative coordinate gives more information on STDOUT (!):

    $ ocr-transform page alto bad-page.xml alto.xml
    Exception in thread "main" java.lang.NullPointerException
            at org.primaresearch.dla.page.converter.PageConverter.handleNegativeCoordinates(PageConverter.java:389)
            at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:216)
            at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:130)

That STDOUT should be shown. In addition, a line break before `STDOUT:` would be good.

**Comment by kba** [comment]
Strange that `STDOUT` apparently isn't captured.

This is how the actual call is implemented
```python
result = subprocess.run(args, check=False, stdout=PIPE, stderr=PIPE)
return result.returncode, result.stdout.decode('utf-8'), result.stderr.decode('utf-8')
```

I cannot spot the reason why it isn't but I'll keep digging.

**Comment by kba** [comment]
special case of #592
