### ISSUE TITLE
OAI-PMH URL does not work

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#653]
I have a URI scheme here that does not seem to be supported yet:

    ocrd -l DEBUG workspace clone "https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045"

```
DEBUG ocrd.resolver.workspace_from_url - workspace_from_url
mets_basename='mets.xml'
mets_url='https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045'
src_baseurl='https://digital.slub-dresden.de'
dst_dir='/home/kmw/nfs/gt_weihnachten'
DEBUG ocrd.resolver.download_to_directory - directory=|/home/kmw/nfs/gt_weihnachten| url=|https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045| basename=|mets.xml| if_exists=|skip| subdir=|None|
INFO ocrd.resolver.download_to_directory - 
	dst_path='/home/kmw/nfs/gt_weihnachten/mets.xml 
	url=https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045
url=%s https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045
directory=%s /home/kmw/nfs/gt_weihnachten
subdir_path=%s .
basename_path=%s mets.xml
ret=%s mets.xml
dst_path=%s /home/kmw/nfs/gt_weihnachten/mets.xml
Traceback (most recent call last):
  File "/home/xbert/ocr-d/ocrd_all/venv/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd/cli/workspace.py", line 133, in workspace_clone
    download=download,
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd/resolver.py", line 158, in workspace_from_url
    workspace = Workspace(self, dst_dir, mets_basename=mets_basename, baseurl=src_baseurl)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd/workspace.py", line 60, in __init__
    mets = OcrdMets(filename=self.mets_target)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd_models/ocrd_mets.py", line 52, in __init__
    super(OcrdMets, self).__init__(**kwargs)
  File "/home/xbert/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd_models/ocrd_xml_base.py", line 35, in __init__
    self._tree.parse(filename)
  File "src/lxml/etree.pyx", line 1881, in lxml.etree._ElementTree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/kmw/nfs/gt_weihnachten/mets.xml", line 36
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: meta line 34 and head, line 36, column 8
```

Seems like `is_oai_response` was never entered...

**Comment by kba** [comment]
I cannot reproduce, with the call above I get

```
ocrd -l DEBUG workspace clone "https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045"
10:34:08.952 DEBUG ocrd.resolver.workspace_from_url - workspace_from_url
mets_basename='mets.xml'
mets_url='https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045'
src_baseurl='https://digital.slub-dresden.de'
dst_dir='/home/kba/build/github.com/OCR-D/monorepo/ocrd_all/core'
10:34:08.953 DEBUG ocrd.resolver.download_to_directory - directory=|/home/kba/build/github.com/OCR-D/monorepo/ocrd_all/core| url=|https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045| basename=|mets.xml| if_exists=|skip| subdir=|None|
10:34:08.954 DEBUG ocrd.resolver.download_to_directory - Downloading URL 'https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045' to '/home/kba/build/github.com/OCR-D/monorepo/ocrd_all/core/mets.xml'
10:34:08.961 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): digital.slub-dresden.de:443
10:34:09.528 DEBUG urllib3.connectionpool - https://digital.slub-dresden.de:443 "GET /oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-511910045 HTTP/1.1" 200 885031
10:34:09.918 INFO ocrd_models.utils.is_oai_content - response data root.tag: '{http://www.openarchives.org/OAI/2.0/}OAI-PMH'
10:34:10.004 INFO ocrd.workspace.save_mets - Saving mets '/home/kba/build/github.com/OCR-D/monorepo/ocrd_all/core/mets.xml'
```

Could this be a network fluke, part of the file missing in transport, hence the XML syntax error?

**Comment by bertsky** [comment]
> Could this be a network fluke, part of the file missing in transport, hence the XML syntax error?

Yes, you're right. This _only_ happens on a virtual server. I'll contact the nw admin.

**Comment by bertsky** [comment]
Sorry, this was not even a network problem: There was a mets.xml file already in the CWD! (Since I did not use `--clobber-mets`, it just skipped the download and tried to instantiate a workspace from it. But the file was buggy...)
