### ISSUE TITLE
handle CMYK images

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#656]
In addition to #627, we need to convert input images of the following color spaces to plain RGB at the beginning:
- CMYK
- HSV
- YCbCr
- LAB

I'm sure there are even more modes which Pillow does not support (see [here](https://imagemagick.org/script/command-line-options.php#colorspace)), but let's concentrate on the modes which the PNG plugin does not support: Compare [this list of Image modes](https://github.com/python-pillow/Pillow/blob/543fa2ceb78103c7ae098900c315748a9283e4d4/src/PIL/Image.py#L244-L272) with [that list of PNG modes](https://github.com/python-pillow/Pillow/blob/543fa2ceb78103c7ae098900c315748a9283e4d4/src/PIL/PngImagePlugin.py#L992-L1008).

**Comment by bertsky** [comment]
Example stack trace:
```
Traceback (most recent call last):
  File "/build/core/ocrd/ocrd/processor/helpers.py", line 101, in run_api
    processor.process()
  File "/build/ocrd_segment/ocrd_segment/replace_original.py", line 78, in process
    mimetype='image/png')
  File "/build/core/ocrd/ocrd/workspace.py", line 820, in save_image_file
    image.save(image_bytes, format=MIME_TO_PIL[mimetype])
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2151, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/dist-
packages/PIL/PngImagePlugin.py", line 1222, in _save
    raise OSError(f"cannot write mode {mode} as PNG") from e
OSError: cannot write mode CMYK as PNG Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PIL/PngImagePlugin.py", line 1220, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'CMYK'
```
