### ISSUE TITLE
resmgr: allow downloading directories

### ISSUE THREAD

**Issue by bertsky** [OCR-D/core#691]
Sometimes (as in the case of Calamari models) resources take the form of directories with multiple files. However, this is currently not supported

```
ocrd resmgr download -n -a ocrd-calamari-recognize https://github.com/Calamari-OCR/calamari_models/tree/master/idiotikon/
INFO ocrd.cli.resmgr - No resources found in registry
INFO ocrd.cli.resmgr - Downloading unregistered resource https://github.com/Calamari-OCR/calamari_models/tree/master/idiotikon/
Traceback (most recent call last):
  File "venv/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/ocrd/cli/resmgr.py", line 99, in download
    content_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

It would be great if resmgr could download these recursively.

**Comment by kba** [comment]
I wanted to avoid having to mess with the GitHub API to get the directory contents, so my preferred way would be to create release tarballs in combination with `path_in_archive` in the `resource_list.yml`, like we do for e.g. the experimental Calamari models.

**Comment by bertsky** [comment]
Yes, my question was misguided. It's a GH specific problem. See https://github.com/Calamari-OCR/calamari_models/issues/11

**Comment by bertsky** [comment]
Maybe not so misguided: This not only applies to GH. And it is even present with **local files**:
```
INFO ocrd.cli.resmgr - No resources found in registry
INFO ocrd.cli.resmgr - Copying unregistered resource v3
Copying  [------------------------------------]    0%INFO ocrd.resource_manager._copy_impl - Copying ./v3

Traceback (most recent call last):
  File "./venv/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "./venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "./venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "./venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "./venv/lib/python3.7/site-packages/ocrd/cli/resmgr.py", line 117, in download
    progress_cb=lambda delta: bar.update(delta))
  File "./venv/lib/python3.7/site-packages/ocrd/resource_manager.py", line 215, in download
    self._copy_impl(url, fpath, progress_cb)
  File "./venv/lib/python3.7/site-packages/ocrd/resource_manager.py", line 173, in _copy_impl
    with open(filename, 'wb') as f_out, open(src_filename, 'rb') as f_in:
IsADirectoryError: [Errno 21] Is a directory: './v3'
```

**Comment by kba** [comment]
> Maybe not so misguided: This not only applies to GH. And it is even present with **local files**:

Can you give me the `ocrd resmgr` call for this, so I can reproduce?

**Comment by bertsky** [comment]
> Can you give me the `ocrd resmgr` call for this, so I can reproduce?

Problem persists even after #792: 
```
ocrd resmgr download -a -n ~/.local/share/ocrd-resources/ocrd-origami-segment/bbz ocrd-origami-segment bbz2
15:20:06.475 INFO ocrd.cli.resmgr - Executable ocrd-origami-segment is not installed, but downloading resources anyway
15:20:06.475 INFO ocrd.cli.resmgr - No resources found in registry
15:20:06.475 INFO ocrd.cli.resmgr - Copying unregistered resource 'bbz2' (~/.local/share/ocrd-resources/ocrd-origami-segment/bbz)
15:20:06.695 INFO ocrd.resource_manager._copy_impl - Copying ~/.local/share/ocrd-resources/ocrd-origami-segment/bbz
Traceback (most recent call last):
  File "/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/lib/python3.6/site-packages/ocrd/cli/resmgr.py", line 142, in download
    progress_cb=lambda delta: bar.update(delta)
  File "/lib/python3.6/site-packages/ocrd/resource_manager.py", line 252, in download
    self._copy_impl(url, fpath, progress_cb)
  File "/lib/python3.6/site-packages/ocrd/resource_manager.py", line 210, in _copy_impl
    with open(filename, 'wb') as f_out, open(src_filename, 'rb') as f_in:
IsADirectoryError: [Errno 21] Is a directory: '~/.local/share/ocrd-resources/ocrd-origami-segment/bbz'
```

**Comment by kba** [comment]
> > Can you give me the `ocrd resmgr` call for this, so I can reproduce?
> 
> Problem persists even after #792:

Please have a look at https://github.com/bertsky/core/pull/3
