### ISSUE TITLE
ocrd workspace bulk-add's FILE_ID generation broken if no pattern is given

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/core#812]
~~~
% ocrd workspace bulk-add \
              --regex '(?P<fileGrp>[^/]+)/page_(?P<pageid>\d+)_.+' \
              --page-id 'PHYS_{{ pageid }}' \
              --file-grp "{{ fileGrp }}" \
              */*.*
                                                             
17:18:25.590 INFO ocrd.cli.workspace.bulk-add - [   0/24] images_enhanced/page_1_1200px-Die_Neue_Zeitung_Erstausgabe_enhanced.png
17:18:25.590 INFO ocrd.cli.workspace.bulk-add - [   1/24] images_enhanced/page_2_6z-1_enhanced.png
Traceback (most recent call last):
  File "/home/mike/.local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/ocrd/cli/workspace.py", line 358, in workspace_cli_bulk_add
    workspace.add_file(fileGrp, ignore=ignore, force=force, **file_dict)
  File "/home/mike/.local/lib/python3.10/site-packages/ocrd/workspace.py", line 365, in add_file
    ret = self.mets.add_file(file_grp, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/ocrd_models/ocrd_mets.py", line 308, in add_file
    raise Exception("File with ID='%s' already exists" % ID)
Exception: File with ID='images.enhanced.page.1.1200px.Die.Neue.Zeitung.Erstausgabe.enhanced.png' already exists
~~~

~~~
% ls *
mets.xml

images:
page_1_1200px-Die_Neue_Zeitung_Erstausgabe.jpg  page_3_AZ_alt.jpg               page_5_faz-erste-ausgabe_druckgut_2005-05-0316.jpg
page_2_6z-1.png                                 page_4_SiegenerZeitung_alt.jpg  page_6_schwaebischedonauz_alt.jpg

images_enhanced:
page_1_1200px-Die_Neue_Zeitung_Erstausgabe_enhanced.png  page_4_SiegenerZeitung_alt_enhanced.png
page_2_6z-1_enhanced.png                                 page_5_faz-erste-ausgabe_druckgut_2005-05-0316_enhanced.png
page_3_AZ_alt_enhanced.png                               page_6_schwaebischedonauz_alt_enhanced.png

xmls:
page_1_1200px-Die_Neue_Zeitung_Erstausgabe.xml  page_3_A_Z_alt.xml              page_5_faz-erste-ausgabe_druckgut_2005-05-0316.xml
page_2_6z-1.xml                                 page_4_SiegenerZeitung_alt.xml  page_6_schwaebischedonauz_alt.xml

xmls_enhanced:
page_1_1200px-Die_Neue_Zeitung_Erstausgabe.xml  page_3_AZ_alt.xml               page_5_faz-erste-ausgabe_druckgut_2005-05-0316.xml
page_2_6_z-1.xml                                page_4_SiegenerZeitung_alt.xml  page_6_schwaebischedonauz_alt.xml
~~~

Deriving the FILE_ID seems to be broken, it is assigned once from the first file. (Adding `-f` yields a `mets.xml` with one file: the last one, with the FILE_ID of the first one.)

**Comment by mikegerber** [comment]
The likely culprit in this case:

https://github.com/OCR-D/core/blob/836eb05e791a196ea7f7e00b6f7438d74ebca582/ocrd/ocrd/cli/workspace.py#L305-L307

**Comment by mikegerber** [comment]
Adding `--file-id 'FILE_{{ fileGrp }}_{{ pageid }}'` solves this.

The first example from `ocrd workspace bulk-add --help` should also trigger this.

**Comment by mikegerber** [comment]
[OCR-D-core-issue-812.zip](https://github.com/OCR-D/core/files/8171328/OCR-D-core-issue-812.zip) – part of the files for the convenience of bug reproduction
